name: trackstar
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.4
  flutter_countdown_timer: ^4.1.0
  flutter_easyloading: ^3.0.5
  dynamic_color: ^1.4.0
  audioplayers: ^1.0.1
  web_socket_channel: ^2.2.0
  json_annotation: ^4.6.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0
  build_runner: ^2.3.0
  json_serializable: ^6.3.1

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon.svg

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/Lobster-Regular.ttf
